debug:
  enabled: True
  api_base: "https://smart-library-app.herokuapp.com"
desks:
  - id : 1
    name: "Desk 1"
    sensor:
      type: 1
      i2c_bus: 1
      i2c_address: 0xa


sensors:
  - type: 1
    name: "Omron D6T"
